exception: remove instanceOf'
well, that was stupid :-) at this point we have the object reference anyway,
therefore we don't have to mess around with mtable-ptr directly.