exception: it's possible that more than one range matches
we have to try all ranges and their potential handlers before doing stack
unwinding. see for example tests/Exception8.java: if we don't try all ranges, we
miss the "generic handler" and therefore the finally statement